title:            Kartikey Sharma
description:      Welcome to my personal website.
# Your site's domain goes here. Leave localhost server or blank when working locally.
#url:              http://localhost:5000
#http://localhost:5000
url:              https://kartikeyrinwa.github.io
disqus_shortname: kartikeyrinwa-github-io

# Owner/author information
owner:
  name:           Kartikey Sharma
  avatar:         kartikey.png
  email:          ksharma@mech.iitd.ac.in
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  linkedin: kartikey-sharma-a79b1457
  google_scholar: IVCufoQAAAAJ
  github: kartikeyrinwa
  cv: /docs/cv.pdf
# Analytics and webmaster tools stuff goes here
#google_analytics: 
#google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
#bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Publications
    url: /publications/
  - title: CV
    url: /cv/
  - title: Talks
    url: /talks/
  - title: Students
    url: /students/
  - title: About
    url: /
#  - title: Posts
#  url: /blog/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/London
future:      true
#pygments:    true
highlighter: rouge
markdown:    kramdown
kramdown:
  extensions: ["strikethrough"]
  
# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

syntax_highlighter_opts:
  line_numbers:
  line_numbers_start: 1
  tab_width: 4
  bold_every: 10
  css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
